### ISSUE TITLE
Question about the packaging steps

### ISSUE THREAD

**Issue by dinuxbg** [VedantParanjape/simppru-build-dockerfiles#1]
I don't see packaging steps in the docker files. Do you package the resulting binaries manually, or I'm missing something?

**Comment by VedantParanjape** [comment]
Hi, this doesn't package anything, it installs pru-gcc to path, and install other dependencies. The docker image is hosted here: https://hub.docker.com/r/simppru/arm32-build-image

This image is then pulled in the workflow and then simpPRU is compiled and packaged in the workflow defined here: https://github.com/VedantParanjape/simpPRU/blob/master/.github/workflows/build_deb.yml

**Comment by dinuxbg** [comment]
Thanks for the clarification.
